apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base namespace configuration
resources:
  - python-api-1-namespace.yaml
  - resource-quota.yaml

# Common labels to be applied to all resources
commonLabels:
  app.kubernetes.io/managed-by: gitops
  gitops.repo: "https://github.com/medaqueno/k8s-lab-gitops.git"
  
# Namespace-specific configurations
configurations:
  - kustomizeconfig.yaml