apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Recursos base de python-api-1
resources:
  - configmap.yaml
  - deployment.yaml

# Labels comunes a la app
commonLabels:
  app: python-api-1
  managed-by: kustomize

# Annotations comunes
commonAnnotations:
  description: "Python API 1 for testing inter-service connectivity"
