apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- deployment.yaml
- service.yaml

commonLabels:
  app: python-api-1
  managed-by: kustomize

images:
- name: ghcr.io/medaqueno/k8s-lab-apps-python-1
  newName: ghcr.io/medaqueno/k8s-lab-apps-python-1
  newTag: "9905698"
