apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: prod-demo-app

commonLabels:
  environment: prod
  tier: application

replicas:
  - name: demo-app
    count: 3
